### ISSUE TITLE
Support for On-premise Solutions

### ISSUE THREAD

**Issue by destroyerofbuilds** [npm/hosted-git-info#11] opened 2015-09-08 21:05 UTC
Should this module support on-premise solutions such as on-premise instances of GitLab, or GitHub Enterprise?

**Comment by destroyerofbuilds** [comment] 2015-09-08 21:06
Related to ajoslin/conventional-changelog#98

**Comment by raido** [comment] 2015-09-11 20:47
I am intrested in this too.

**Comment by jokeyrhyme** [comment] 2016-12-20 05:37
I've been wondering whether this can be done by making an HTTP request to the host and inspecting the headers?

-   GitLab: `curl -ILv https://gitlab.com/explore`: response has a Set-Cookie header for the "_gitlab_session" cookie (confirmed the same for self-hosted)

-   GitHub: `curl -ILv https://github.com`: response has X-GitHub-Request-Id header (no idea about enterprise / self-hosted)

-   BitBucket: `curl -ILv https://bitbucket.org/account/signin/`: no identifying material in response

The tricky part about self-hosted repositories is that the hosts / URLs could have nothing to do with the git hosting service, so we'd need to query _something_ to figure it out.

**Comment by iarna** [comment] 2017-03-17 23:25
While on premise solution support would be pretty cool, I'm pretty sure there's no way to do it. Having to do a capabilities check of a server is not an option for this module, however.

As I don't believe this is possible, I'm going to close this, but feel free to continue discussing it (and if you do figure something out, open up a new issue!)

**Closed by iarna** 2017-03-17 23:25 UTC

**Comment by mehulkar** [comment] 2019-02-16 01:30
@iarna 👋. I'm jumping in late here, but could explain why there isn't a way to do it? I'm looking in particular at the `fromUrl` function. It looks like it just parses a string, so if we ignore the `host` and assume the rest of the path is in GH format it should be possible?

**Comment by nicolechung** [comment] 2023-06-21 15:46
Late to this, but I have a question...is it possible to add your own host with `hostedGitinfo.addHost('enterpriseHost', ...hostData)`?

If so, I think this would suit my needs and I'd be happy to PR to update the docs with this.

**Comment by nicolechung** [comment] 2023-06-21 18:53
I think it would require exporting `maybeJoin` and `maybeEncode` however...looks like all the hosts supply this.
